(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var U0=function(a){a.ea("cardstatechange",a.Ph()&&a.Nl()?1:0)},V0=function(a,b){var c=g.La(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},ETa=function(a){var b=g.Rm(a);
a=g.Um(a);return new g.Gm(b.x,b.y,a.width,a.height)},FTa=function(a){return Math.pow(a,3)},GTa=function(a){return 3*a*a-2*a*a*a},Y0=function(a){a=g.Oa(a);
delete W0[a];g.Qf(W0)&&X0&&X0.stop()},ITa=function(){X0||(X0=new g.L(function(){HTa()},20));
var a=X0;a.isActive()||a.start()},HTa=function(){var a=g.Ta();
g.Bf(W0,function(b){JTa(b,a)});
g.Qf(W0)||ITa()},Z0=function(a,b,c,d){g.Pp.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.J=d;this.coords=[];this.progress=this.K=0;this.D=null},JTa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;KTa(a,a.progress);1==a.progress?(a.j=0,Y0(a),a.onFinish(),a.Ry()):a.Nc()&&a.sE()},KTa=function(a,b){"function"===typeof a.J&&(b=a.J(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},LTa=function(a,b){g.rf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},$0=function(a,b,c,d,e){Z0.call(this,b,c,d,e);
this.element=a},a1=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
$0.call(this,a,b,c,d,e)},b1=function(a){g.G.call(this);
this.u=a||window;this.j=[]},c1=function(a){return a.baseUrl||null},d1=function(a,b){return g.Yn(g.Vl(a,b),function(c){return!!c})},MTa=function(a,b,c){function d(Pa){var Sa=Pa.hovercardButton;
if(!Sa)return null;Sa=Sa.subscribeButtonRenderer;if(!Sa)return null;var ac=f(Sa.unsubscribedButtonText),zb=f(Sa.subscribedButtonText);if(Sa.subscribed){var yc=f(Sa.subscriberCountWithUnsubscribeText);var Rc=f(Sa.subscriberCountText)}else yc=f(Sa.subscriberCountText),Rc=f(Sa.subscriberCountWithSubscribeText);var gd=null;if(Pa.signinEndpoint){gd=V0(Pa,"signinEndpoint","webNavigationEndpointData","url");if(!gd){var he,Kf,Ab;gd=null==(he=Sa.signInEndpoint)?void 0:null==(Kf=he.commandMetadata)?void 0:
null==(Ab=Kf.webCommandMetadata)?void 0:Ab.url}if(!gd)return null}return ac&&(zb||gd)?{subscribed:Sa.subscribed,subscribeText:ac,subscribeCount:yc,unsubscribeText:zb,unsubscribeCount:Rc,enabled:Sa.enabled,signinUrl:gd,classic:Pa.useClassicSubscribeButton}:null}
function e(Pa){if(Pa){var Sa=[],ac=Pa.videoId;ac&&Sa.push("v="+ac);(ac=Pa.playlistId)&&Sa.push("list="+ac);(Pa=Pa.startTimeSeconds)&&Sa.push("t="+Pa);return"/watch?"+Sa.join("&")}}
function f(Pa){if(!Pa)return null;var Sa=Pa.simpleText;return Sa?Sa:Pa.runs?g.Vl(Pa.runs,function(ac){return ac.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,t=null,v=null,x=null,y=!1,z=null,E=null,J=null,I=null,N=null,Z=null;if("VIDEO"===k)l.urlEndpoint?m=l.urlEndpoint.url:(Z=l.watchEndpoint,m=e(Z)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===k)l.urlEndpoint?m=l.urlEndpoint.url:(Z=l.watchEndpoint,m=e(Z)),n=!1,q=a,v=f(b.playlistLength);
else if("CHANNEL"===k){if(y=V0(l,"browseEndpoint","browseId"))x=y,m="/channel/"+x;n=!1;q="new";(y=!!b.isSubscribe)?z=d(b):E=f(b.subscribersText)}else"WEBSITE"===k?((J=V0(l,"urlEndpoint","url"))&&(m=J),n=!0,q="new",J=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===k&&(b.productPrice&&(I=f(b.productPrice)),b.additionalFeesText&&(N=f(b.additionalFeesText)),(n=V0(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=V0(b,"title","accessibility","accessibilityData","label");var K=b.endpoint?b.endpoint.clickTrackingParams:
null,ra="";if(b.metadata){var za=f(b.metadata);za&&(ra=za)}return{id:"element-"+c,type:k,title:f(b.title),metadata:ra,callToAction:f(b.callToAction),YM:b.image,iconUrl:J,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,isLiveVideo:p,playlistLength:v,channelId:x,subscribeButton:z,subscribersText:E,isSubscribe:y,targetUrl:m||null,KW:n,sessionData:K?{itct:K}:null,s0:q,
Yw:a?a:null,isPlaceholder:b.isPlaceholder,impressionUrls:d1(b.impressionUrls||[],c1),xW:d1(b.hovercardShowUrls||[],c1),clickUrls:d1(l.loggingUrls||[],c1),visualElement:g.Mv(b.trackingParams),productPrice:I,additionalFeesText:N,watchEndpoint:Z||null}},e1=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:d1(a.impressionUrls||[],c1),elements:d1(a.elements||[],function(d,e){return MTa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Mv(a.trackingParams));return c},f1=function(a){g.cK.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.K=[];this.Y=!0;this.J=0;a=a.V();this.S=g.xC(a)||g.BC(a);this.events=new g.iA(this);g.H(this,this.events);this.events.T(this.player,g.Kw("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.Lw("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.xb);this.events.T(window,"focus",this.q_);this.load();var b=g.di("STYLE");(g.Ph("HEAD")[0]||document.body).appendChild(b);g.qf(this,function(){g.hi(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},NTa=function(a){return a.player.getVideoData().D?"current":a.S?"new":"current"},g1=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},OTa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=e1(f,NTa(a))));h1(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.Or;d&&(c.postParams={ad_tracking:d});if(b=g.iwa(b))if(b=g.Tg(b),b=g.Pg(b))a.B=g.Gr(b,c)},h1=function(a,b,c){c=void 0===c?!0:c;
a.player.Nf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&PTa(a);c=[];d=new g.Iw(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.V({G:"div",L:"ytp-ce-shadow"}),g.EJ(a.player,a.u.element,4),a.C=new g.JH(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=QTa(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.EJ(a.player,f.element,4);var k=new g.Iw(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);RTa(a,
f,e)}else g.Jv(new g.Is("buildEndscreenElement null",e))}a.player.je(c);a.xb()}},PTa=function(a){var b=g.Sv(),c=g.Tv();
c&&b&&a.endscreen.visualElement&&g.Xv(void 0,c,b,[a.endscreen.visualElement])},QTa=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",Ea:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.Yw||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:i1(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:j1(a,b.targetUrl),tabindex:"-1"},U:[{G:"div",Ea:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.Tp(b.title||"")},oa:b.title},{G:"div",L:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
oa:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={G:"div",Ea:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.Yw||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:i1(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:j1(a,b.targetUrl),tabindex:"-1"},U:[{G:"div",Ea:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.Tp(b.title||"")},oa:b.title},{G:"div",L:"ytp-ce-playlist-count",
U:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",oa:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={G:"div",Ea:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.Yw||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",
U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"a",Ea:["ytp-ce-channel-title","ytp-ce-link"],W:{href:j1(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Tp(b.title||"")},oa:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",U:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",oa:b.subscribersText}:"",b.metadata?{G:"div",Ea:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],oa:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:i1(b)}]};c=new g.V(c);var d=g.Sh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.M(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.hL(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ea:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.Yw||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",
U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-website-title",W:{dir:g.Tp(b.title||"")},oa:b.title},{G:"div",L:"ytp-ce-website-metadata",oa:b.metadata},{G:"a",Ea:["ytp-ce-website-goto","ytp-ce-link"],W:{href:j1(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:i1(b)},{G:"div",L:"ytp-ce-expanding-icon",W:STa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",U:[{G:"div",L:"ytp-ce-merchandise-price",oa:b.productPrice}]},b.additionalFeesText&&c.U.push({G:"div",L:"ytp-ce-merchandise-additional-fees",oa:b.additionalFeesText})),a={G:"div",Ea:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.Yw||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},
{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-merchandise-title",W:{dir:g.Tp(b.title||"")},oa:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",oa:b.metadata},{G:"a",Ea:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:j1(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:i1(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",
U:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",oa:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.M(c.element,"ytp-ce-placeholder");return c},i1=function(a){if(a.YM)var b=a.YM.thumbnails;
return STa(b?b[b.length-1].url:null)},STa=function(a){return a?{style:"background-image: url("+a+")"}:{}},RTa=function(a,b,c){function d(m){m&&(b.Ma("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",k))}
function e(m){a.J+=m;0<a.J?(g.M(b.element,"ytp-ce-force-expand"),k1(a,c.id,!0)):(g.Gp(b.element,"ytp-ce-force-expand"),g.Gp(b.element,"ytp-ce-element-hover"),k1(a,c.id,!1))}
function f(){e(1)}
function k(){e(-1)}
b.Ma("mouseenter",function(){l1(a,b,c)});
b.Ma("mouseleave",function(){m1(a,b,c)});
a.player.V().isMobile||b.Ma("click",function(){g.M(b.element,"ytp-ce-element-hover")});
b.Ma("click",function(m){TTa(a,c,m)});
b.Ma("keypress",function(m){TTa(a,c,m)});
b.Ma("focus",function(){l1(a,b,c)});
b.Ma("blur",function(){m1(a,b,c)});
b.Ma("touchstart",function(){l1(a,b,c)});
var l=g.Uh("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Gp(b.element,"ytp-ce-element-hover");g.Gp(b.element,"ytp-ce-force-expand")});
b.Ma("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.Uh("ytp-sb-subscribe",b.element));d(g.Uh("ytp-sb-unsubscribe",b.element));b.Ma("focus",f);b.Ma("blur",k)},TTa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Ep(d,"ytp-ce-element");){g.Ep(d,"subscribe-label")&&n1(a,b);
if(g.Ep(d,"ytp-ce-channel-subscribe"))return;d=g.ii(d)}if(!d||g.Ep(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])m1(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.s0)n1(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Tg(j1(a,b.targetUrl)),g.iI(g.Pg(c),void 0,b.sessionData);else{var e=g.RC(a.player.V())||a.player.getVideoData().D,f=function(){var k=j1(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.or(k);e&&n&&(n.v||n.list)?
a.player.ol(n.v,l,n.list,!1,void 0,m||void 0):g.hI(k,l)};
n1(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},j1=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.bD(a)+b}else return"";return b},l1=function(a,b,c){g.Ep(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.M(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.L(function(){g.M(b.element,"ytp-ce-element-hover")},200)).start():g.M(b.element,"ytp-ce-element-hover"),o1(a,c.xW),k1(a,c.id,!0))},m1=function(a,b,c){g.Gp(b.element,"ytp-ce-element-hover");
g.Gp(b.element,"ytp-ce-force-expand");k1(a,c.id,!1)},k1=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.O(a.j[e].element,"ytp-ce-element-shadow-show",c)},o1=function(a,b,c){function d(){f||(e++,e===b.length&&(k.stop(),c&&c()))}
if(!b||0===b.length||g1(a))c&&c();else{b=UTa(a,b);var e=0,f=!1,k=new g.L(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Nt(b[a],d)}},n1=function(a,b,c){o1(a,b.clickUrls,c);
(a=g.Tv())&&b.KW&&g.cw(a,b.visualElement)},UTa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(VTa(b[d],c));return a},VTa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},WTa=function(a){return"string"===typeof a?a:""},p1=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},XTa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},q1=function(a){return a.value?a.value:null},r1=function(a){if(!a)return null;
var b=g.Tg(WTa(a.value));b=g.Pg(b);if(!b)return null;var c=p1(a.target,YTa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new XTa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},ZTa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},bUa=function(a){if(!a)return null;
var b=p1(a.type,$Ta),c=p1(a.trigger,aUa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=r1(a?a:null);return b?new ZTa(b,c,a):null},cUa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},eUa=function(a){return(a=dUa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},dUa=function(a,b){return g.Pb(a.action,b)},fUa=function(a,b){this.context=a;
this.j=b},t1=function(a){return a.customMessage?s1("div","iv-card-message",a.customMessage):""},u1=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",W:{style:a},U:c}},v1=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(s1("li","",c.value));return{G:"ul",L:"iv-card-meta-info",U:b}},s1=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Tp(c);return{G:a,W:b,oa:c}},gUa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.jx&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.jx+");");c.dir=g.Tp(a.customMessage);var d=[{G:"span",oa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ea:b,W:c,U:d}},w1=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},hUa=function(a,b){this.merchant=a;
this.price=b},iUa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},jUa=function(a,b){return b?b:iUa(a)?"current":"new"},x1=function(a,b){g.G.call(this);
var c=this;this.element=a;this.context=b;this.kb=!1;this.Ua=new Map;this.Xa=new Map;this.context.I.addEventListener(g.Kw("annotations_module"),function(d){(d=c.Ua.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.Lw("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)})},y1=function(a,b,c,d,e,f,k){a.context.j.Ma(b,"click",function(l){a.tE(c,d,e,f||[],k||0,l)});
a.context.j.Ma(b,"touchstart",function(){a.kb=!1});
a.context.j.Ma(b,"touchmove",function(){a.kb=!0})},kUa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},z1=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
nR:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
oD:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},C1=function(a,b,c){x1.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.La=this.Kb=this.B=this.isInitialized=!1;this.va=null;this.cards=[];this.rb=this.S=this.Ia=this.D=this.Ta=this.j=null;this.Z=[];this.ma=this.K=this.kf=this.Ga=null;this.J=0;this.Aa=new g.L(function(){},c.X.cf?4E3:3E3);
g.H(this,this.Aa);this.ib=new g.L(function(){});
g.H(this,this.ib);this.ra=new fUa(c,function(e,f,k,l,m,n){y1(d,e,f,k,l,m,n)});
this.Y=new g.V({G:"div",L:"iv-drawer",W:{id:"iv-drawer"},U:[{G:"div",L:"iv-drawer-header",W:{"aria-role":"heading"},U:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ea:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Nascondi schede",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.H(this,this.Y);this.C=this.Y.element;this.gb=new g.JH(this.Y,330);g.H(this,this.gb);this.Ib=g.Uh("iv-drawer-header-text",this.C);this.u=g.Uh("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Kb&&A1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Kb=d.B)&&B1(d)});
this.I.addEventListener("videodatachange",this.Bp.bind(this))},lUa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){A1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){B1(a)});
var c=b.headerText;g.ki(a.Ib,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ga=g.Mv(b.trackingParams);a.K=g.Mv(b.closeTrackingParams);a.kf=g.Mv(b.iconTrackingParams)},mUa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J,d=a.I.V().experiments.jb("enable_error_corrections_infocard");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){d=b.teaser.simpleCardTeaserRenderer;var e=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.Pw(d.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,tracking:{},Ol:null,dj:d.trackingParams?g.Mv(d.trackingParams):null,kf:e&&e.trackingParams?g.Mv(e.trackingParams):null,imageUrl:"",displayDomain:null,
showLinkIcon:!1,jx:null,title:"",customMessage:"",url:null,onClickCommand:d.onTapCommand||null};D1(a,b)}else if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.Pw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:E1(a,
c,b,d),sponsored:!1,tracking:z1(d,e,d.command),Ol:d.trackingParams?g.Mv(d.trackingParams):null,dj:e.trackingParams?g.Mv(e.trackingParams):null,kf:f&&f.trackingParams?g.Mv(f.trackingParams):null,imageUrl:F1(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.Pw(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,jx:null,title:d.title?g.Pw(d.title):"",customMessage:d.callToAction?g.Pw(d.callToAction):"",url:d.command.urlEndpoint.url?r1({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:d.command.urlEndpoint.url}):null,onClickCommand:null};D1(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.Pw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:E1(a,
c,b,d),sponsored:!1,tracking:z1(d,e,d.endpoint),Ol:d.trackingParams?g.Mv(d.trackingParams):null,dj:e.trackingParams?g.Mv(e.trackingParams):null,kf:f&&f.trackingParams?g.Mv(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.Pw(d.customText):null,profileImageUrl:F1(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.Pw(d.channelName):"",metaInfo:[d.subscriberCountText?g.Pw(d.subscriberCountText):""],url:r1({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId}),onClickCommand:null};D1(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.Pw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:E1(a,c,b,d),sponsored:!1,tracking:z1(d,e,d.action),Ol:d.trackingParams?g.Mv(d.trackingParams):null,dj:e.trackingParams?g.Mv(e.trackingParams):null,kf:f&&f.trackingParams?g.Mv(f.trackingParams):null,Mz:F1(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.Pw(d.customMessage):null,playlistVideoCount:g.Pw(d.playlistVideoCount),title:d.playlistTitle?g.Pw(d.playlistTitle):"",metaInfo:[d.channelName?
g.Pw(d.channelName):"",d.videoCountText?g.Pw(d.videoCountText):""],url:r1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:kUa(d.action)}),onClickCommand:null};D1(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.Pw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:E1(a,c,b,d),sponsored:!1,tracking:z1(d,e,d.action),Ol:d.trackingParams?g.Mv(d.trackingParams):null,dj:e.trackingParams?g.Mv(e.trackingParams):null,kf:f&&f.trackingParams?g.Mv(f.trackingParams):null,Mz:F1(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.Pw(d.lengthString):null,customMessage:d.customMessage?g.Pw(d.customMessage):null,title:d.videoTitle?g.Pw(d.videoTitle):"",metaInfo:[d.channelName?
g.Pw(d.channelName):"",d.viewCountText?g.Pw(d.viewCountText):""],isLiveNow:!!d.badge,url:r1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:kUa(d.action)}),onClickCommand:null};D1(a,b)}a.J++},F1=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},E1=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},oUa=function(a,b){if(b=nUa(a,b))b===a.j&&(a.j=null),a.I.removeCueRange(b.card.id),g.hi(b.qF),g.Xb(a.cards,b),a.IA(),G1(a)},A1=function(a,b,c){if(!a.B){a.gb.show();
a.Ta=new g.L(function(){g.M(a.context.I.getRootNode(),g.rP.IV_DRAWER_OPEN)},0);
a.Ta.start();a.va=g.ou(a.u,"mousewheel",function(k){a.Aa.start();k.preventDefault();k=k||window.event;var l=0;"MozMousePixelScroll"==k.type?l=0==(k.axis==k.HORIZONTAL_AXIS)?k.detail:0:window.opera?l=k.detail:l=0==k.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?k.wheelDeltaY/-30:k.wheelDeltaY/-1.2:k.wheelDelta/-1.6:k.wheelDeltaY/-3;if(k=l)a.u.scrollTop+=k});
a.B=!0;var d=g.Tv();d&&a.Ga&&a.K&&g.aw(d,[a.Ga,a.K]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.KO||(f.KO=!0,pUa(a.context.logger,f.card.tracking.impression,b)),d&&g.aw(d,[f.card.Ol]);U0(a.I);c&&(a.D=new g.L(function(){a.Ia=a.S;a.rb.focus()},330),a.D.start())}},B1=function(a){a.B&&(a.gb.hide(),g.pu(a.va),a.va=null,g.Gp(a.context.I.getRootNode(),g.rP.IV_DRAWER_OPEN),a.B=!1,U0(a.I),a.D&&a.D.stop(),a.D=new g.L(function(){a.Ia&&(a.Ia.focus(),a.Ia=null)},330),a.D.start())},
rUa=function(a){g.Fp(a.element,[g.rP.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.EJ(a.I,a.C,5);qUa(a);a.S=g.Uh("ytp-cards-button",a.I.getRootNode());a.rb=g.Uh("iv-drawer-close-button",a.C);a.isInitialized=!0},qUa=function(a){var b=g.Uh("iv-drawer-close-button",a.C);
a.context.j.Ma(b,"click",a.iV,a);a.context.j.Ma(a.u,"touchend",function(){a.Aa.start()});
a.context.j.Ma(a.u,"scroll",a.vV,a);a.context.u.subscribe("onHideControls",function(){a.La=!0});
a.context.u.subscribe("onShowControls",function(){a.La=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.La=g.Ep(a.I.getRootNode(),"ytp-autohide")});
a.Z.push(g.Iu("iv-button-shown",a.TW,a));a.Z.push(g.Iu("iv-button-hidden",a.SW,a));a.Z.push(g.Iu("iv-teaser-shown",a.NT,a));a.Z.push(g.Iu("iv-teaser-hidden",a.UW,a));a.Z.push(g.Iu("iv-teaser-clicked",a.LT,a))},sUa=function(a,b){var c,d=null==(c=a.I.getVideoData())?void 0:c.multiMarkersPlayerBarRenderer;
if(null==d?0:d.markersMap){var e;for(c=0;(null==(e=d)?void 0:e.markersMap.length)>c;c++){var f=void 0,k=null==(f=d)?void 0:f.markersMap[c];if("ERROR_CORRECTION_MARKERS"===k.key&&(f=void 0,(k=null==(f=k.value)?void 0:f.markers)&&0<k.length))return d=void 0,b.startMs=(null==(d=k[0].markerRenderer)?void 0:d.timeRangeStartMillis)||0,a.ma=null,!0}}a.ma=b;return!1},D1=function(a,b){if(b.onClickCommand&&b.onClickCommand.changeEngagementPanelVisibilityAction&&"engagement-panel-error-corrections"===b.onClickCommand.changeEngagementPanelVisibilityAction.targetId){a.ma=
b;
var c=!0}else c=!1;if(!c||sUa(a,b))if(c=tUa(a,b)){var d={card:b,qF:c.element,KO:!1};if(!b.onClickCommand){a.isInitialized||rUa(a);oUa(a,b.id);var e=uUa(a,d);g.dc(a.cards,e,0,d);c.Ba(a.u,e);a.IA()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,G1(a),vUa(a,d),A1(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&wUa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){wUa(a,d)}),G1(a))}},tUa=function(a,b){switch(b.type){case "simple":a=
a.ra;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",oa:b.displayDomain}:void 0;var d=gUa(b);c={G:"div",Ea:["iv-card"],U:[{G:"a",L:"iv-click-target",W:{href:b.url?q1(b.url)||"":""},U:[u1(b.imageUrl,c),{G:"div",L:"iv-card-content",U:[s1("h2",void 0,b.title),d]}]}]};c=new g.V(c);w1(a,g.Th("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.ra,c={G:"div",Ea:["iv-card","iv-card-channel"],U:[{G:"a",Ea:["iv-click-target"],W:{href:q1(b.url)||"","data-ytid":b.channelId},U:[u1(b.profileImageUrl),
{G:"div",L:"iv-card-content",U:[t1(b),{G:"h2",L:"iv-card-primary-link",oa:b.title},v1(b)]}]}]},c=new g.V(c),w1(a,g.Th("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.ra,c={G:"div",Ea:["iv-card","iv-card-playlist"],U:[{G:"a",L:"iv-click-target",W:{href:q1(b.url)||""},U:[u1(b.Mz,{G:"div",L:"iv-card-image-overlay",U:[{G:"span",L:"iv-card-playlist-video-count",oa:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",U:[t1(b),s1("h2","iv-card-primary-link",b.title),v1(b)]}]}]},c=new g.V(c),
w1(a,g.Th("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.ra;var e=!g.Tb(b.offers);c=["iv-card"];d="";var f=gUa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",oa:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",oa:f.merchant}),f={G:"div",U:e});e=b.url?q1(b.url)||"":"";c={G:"div",Ea:c,W:{tabindex:"0"},U:[{G:"a",Ea:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",U:[b.sponsored?{G:"div",L:"iv-card-sponsored",U:["Sponsorizzati",{G:"div",L:"iv-ad-info-container",U:[{G:"div",L:"iv-ad-info",oa:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",U:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",W:{href:e},U:[s1("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.di("span");g.ki(d,"Visualizzi questo prodotto perch\u00e9 riteniamo sia attinente al video. Google potrebbe ricevere un compenso da parte del commerciante.");
c.Od(d,"adInfo");w1(a,g.Th("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.ra,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",oa:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ea:["yt-badge","yt-badge-live"],oa:"IN DIRETTA ORA"}:null,e={G:"div",Ea:["iv-card","iv-card-video"],U:[{G:"a",L:"iv-click-target",W:{href:(null==(c=b.url)?void 0:q1(c))||""},U:[u1(b.Mz,d),{G:"div",L:"iv-card-content",U:[t1(b),s1("h2","iv-card-primary-link",b.title),v1(b),f]}]}]},c=new g.V(e),w1(a,
g.Th("iv-click-target",c.element),b,b.url),c;default:return null}},uUa=function(a,b){if(0===a.cards.length)return 0;
a=g.Qb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},xUa=function(a){return a.j?"productListing"===a.j.card.type:g.Wl(a.cards,function(b){return"productListing"===b.card.type})},G1=function(a){g.O(a.I.getRootNode(),"ytp-cards-shopping-active",xUa(a))},wUa=function(a,b){if(!g.Ep(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Tv(),d=a.j?a.j.card.kf:a.kf;
c&&d&&g.bw(c,[d]);a.j=b;G1(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.I.Gv(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.ib.isActive()||((!a.B||!a.Aa.isActive()&&a.La)&&vUa(a,b),a.ib.start(910+b.card.teaserDurationMs))}},vUa=function(a,b){a.Y.sb?(b=new Z0([0,
a.u.scrollTop],[0,b.qF.offsetTop],600,GTa),a.context.B.Ma(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ma(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.YG(a.Y,!0),a.u.scrollTop=b.qF.offsetTop,g.YG(a.Y,!1))},H1=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},nUa=function(a,b){return g.Pb(a.cards,function(c){return c.card.id===b})},I1=function(a,b,c){x1.call(this,a,b);
this.annotation=c;this.isActive=!1},yUa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},J1=function(a,b,c){I1.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.j=this.J=this.D=null},zUa=function(a,b){var c=void 0===c?0:c;
var d=ETa(b).width;g.Pm(b,d);c=new a1(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,FTa);g.H(a,c);a.context.B.Ma(c,"begin",function(){g.Vm(b,!0)});
c.play()},CUa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ea:["iv-branding-context-name"],oa:b.channel_name}),d=a.createElement({G:"div",Ea:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.hL(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.I),a.j.Ba(d));var f=a.createElement({G:"div",Ea:["iv-branding-context-subscribe-caret"]}),k=a.createElement({G:"div",Ea:["branding-context-container-inner"]});
k.appendChild(f);k.appendChild(c);k.appendChild(d);g.Vm(k,!1);var l=a.createElement({G:"div",Ea:["branding-context-container-outer"]});l.appendChild(k);g.Jm(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.L(function(){AUa(a,k,l)},500);
g.H(a,a.B);a.context.j.Ma(a.element,"mouseover",function(){BUa(a,k,l,f,b.image_height)});
a.context.j.Ma(a.element,"mouseout",function(){a.B.start()})}},BUa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Um(b);a.j||(b.style.width=g.Om(f.width,!0),c.style.width=g.Om(f.width,!0));g.Jm(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Jm(d,"right","1px");a.C=!0;g.Vm(b,!0);a.D=new g.L(function(){g.M(this.element,"iv-branding-active")},0,a);
a.D.start()}},AUa=function(a,b,c){g.Gp(a.element,"iv-branding-active");
a.J=new g.L(function(){g.Vm(b,!1);a.j||(c.style.width=g.Om(0,!0))},250);
a.J.start();a.C=!1},DUa=function(a,b,c,d,e,f,k){this.j=a;
this.B=b;this.X=c;this.videoData=d;this.logger=e;this.I=f;this.u=k},K1=function(a,b,c){I1.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.Y=!1;this.J=5E3;this.u=this.B=this.j=this.C=null;this.K=this.createElement({G:"div",Ea:["iv-promo-contents"]});this.D=new g.L(function(){d.j.setAttribute("aria-hidden","true");g.Vm(d.B,!1);g.Vm(d.u,!0)},700,this);
g.H(this,this.D)},EUa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promozione");a.element.tabIndex=0;var e=eUa(a.annotation),f=b.image_url;if(f){var k=a.createElement({G:"div",Ea:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",W:{src:f,"aria-hidden":"true"}});k.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",oa:b.video_duration}),k.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",oa:b.playlist_length.toString()}),k.appendChild(f));e&&y1(a,k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.qh(f,q1(e)),a.j=f):a.j=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",U:[{G:"strong",
oa:b.text_line_1}]});var m=a.createElement({G:"p",U:[{G:"span",L:"iv-promo-link",oa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ea:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ea:["iv-button","iv-promo-button"],U:[{G:"span",L:"iv-button-content",oa:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&y1(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.M(a.j,
"iv-click-target");e&&y1(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",U:[{G:"span",oa:b.text_line_1}]}),m=a.createElement({G:"p",U:[{G:"strong",oa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ea:["yt-badge","iv-promo-badge-live"],oa:"IN DIRETTA ORA"})),g.M(a.j,"iv-click-target"),e&&y1(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.K.appendChild(a.j);
p&&a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ea:["iv-promo-expand","ytp-button"]});a.u.title="Espandi";a.context.j.Ma(a.u,"click",function(q){L1(a,5E3,q)});
c.appendChild(a.u);g.Vm(a.u,!1);a.context.j.Ma(a.element,"mouseover",a.bW,a);a.context.j.Ma(a.element,"mouseout",a.aW,a);a.context.j.Ma(a.element,"touchend",function(q){L1(a,5E3,q)});
a.B=a.createElement({G:"button",Ea:["iv-promo-close","ytp-button"]});a.B.title="Chiudi";a.context.j.Ma(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.WV:a.VV,a);c.appendChild(a.B);g.Fp(a.element,d);k&&(a.element.appendChild(k),n&&k.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},L1=function(a,b,c){c.stopPropagation();
FUa(a);GUa(a,b);a.j.focus()},HUa=function(a){a.isCollapsed||a.S||a.C||(g.M(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},FUa=function(a){a.D.stop();
a.isCollapsed&&(g.Hp(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Vm(a.u,!1),g.Vm(a.B,!0))},GUa=function(a,b){a.C||(a.C=g.Ei(function(){M1(this);
HUa(this)},b,a))},M1=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},IUa=function(a){this.I=a},pUa=function(a,b,c){b&&(c?N1(a,b.map(function(d){return g.qp(d,c)})):N1(a,b))},N1=function(a,b,c,d){var e=1,f=void 0,k=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(k),l=!0,c())};
k=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Nt(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},O1=function(a){g.cK.call(this,a);
var b=this;this.loadNumber=0;this.J={};this.logger=new IUa(this.player);this.D=new g.iA(this);this.C=this.Im=null;this.events=new g.iA(this);this.K=this.j=null;this.S=[];g.H(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.D.T(this.player,"resize",function(d){b.ea("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.OT,this);this.subscribe("resize",this.vC,this);this.player.V().Z.subscribe("vast_info_card_add",this.WP,this);g.H(this,this.events);this.Y=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.V({G:"div",Ea:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.EJ(this.player,this.u.element,4);this.u.hide();this.B=new g.V({G:"div",Ea:["ytp-iv-video-content"]});g.H(this,this.B);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.Y);this.B.element.appendChild(a);this.Js()&&this.load();var c=this.createElement({G:"style"});(g.Ph("HEAD")[0]||document.body).appendChild(c);g.qf(this,function(){g.hi(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},JUa=function(a){a=a.createElement({G:"div",
Ea:["annotation","annotation-type-custom"]});g.Vm(a,!1);return a},KUa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.YG(a.u,b);g.YG(a.B,b)},LUa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ma(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(LUa(a,e))}return c},OUa=function(a){var b=a.player.getVideoData();
if(b.Ua){var c=a.player.V().Z.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,k){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(k=g.Ar(k)&&k.responseXML?k.responseXML:null)&&P1(a,k)}};
g.Wr()&&(d.onFinish=MUa(a,d.onFinish));d.postParams={ic_only:"1"};NUa(d,c);g.Gr(b.Ua,d)}}},NUa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.kx&&(a.postParams.ic_coll=b.kx);b.NA&&(a.postParams.ic_xml=b.NA);b.Pz&&(a.postParams.ic_track=b.Pz)},PUa=function(a){var b=new g.V({G:"div"});
g.Vm(b.element,!1);var c=new C1(a.player,b.element,Q1(a));g.H(c,b);b.Ba(a.u.element);c.zz();return c},Q1=function(a){if(!a.K){var b=new b1(a);
g.H(a,b);var c=new g.Tk(a);g.H(a,c);a.K=new DUa(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Ne)}return a.K},P1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Tv();if(e){var f=g.Sv();f&&g.Xv(void 0,e,f,[g.Mv(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=LUa(a,b[d]);e=null;try{if(f){var k=f.id,l=/.+/;var m="string"===typeof k&&null!=l&&null!=k&&k.match(l)?k:"";var n=p1(f.type,QUa),p=p1(f.style,RUa),q=WTa(f.data),t=0!==q.length?JSON.parse(q):{};var v=f.action;f=bUa;if(null==v)var x=null;else if(g.La(v)){l=[];for(var y=g.r(v),z=y.next();!z.done;z=y.next()){var E=f(z.value);
E&&l.push(E)}x=l}else{var J=f(v);x=J?[J]:[]}e=m&&n?new cUa(m,n,p,x,t):null}else e=null}catch(za){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=JUa(f),N=null;switch(l.type){case "branding":if(f.player.V().Oc)break;f.u.element.appendChild(I);N=new J1(I,Q1(f),l);break;case "promotion":g.EJ(f.player,I,4),N=new K1(I,Q1(f),l)}N&&N.zz();if(f=N)g.H(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=PUa(a),g.H(a,a.j));if("card"===e.type){c=a.j;var Z=e&&e.data&&e.data.card_type;
f=e.data;if(Z)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,nR:l.teaser_impression,oD:l.teaser_click},I=f.tracking_params||{},N=null,Z){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ol:I.card?g.Mv(I.card):null,dj:I.teaser?g.Mv(I.teaser):null,kf:I.icon?g.Mv(I.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:r1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};D1(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,
Ol:I.card?g.Mv(I.card):null,dj:I.teaser?g.Mv(I.teaser):null,kf:I.icon?g.Mv(I.icon):null,Mz:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:r1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};D1(c,e);break;case "productListing":f.signin_url&&(N=r1({target:"current",value:f.signin_url}));Z=[];for(var K=f.offers||[],ra=0;ra<K.length;ra++)Z.push(new hUa(g.Fh(K[ra].merchant),
g.Fh(K[ra].price)));e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ol:I.card?g.Mv(I.card):null,dj:I.teaser?g.Mv(I.teaser):null,kf:I.icon?g.Mv(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,jx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:r1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),mja:N,lja:f.signin_title?f.signin_title:void 0,kja:f.signin_message?f.signin_message:void 0,offers:Z,onClickCommand:null};D1(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ol:I.card?g.Mv(I.card):
null,dj:I.teaser?g.Mv(I.teaser):null,kf:I.icon?g.Mv(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,jx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:r1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};D1(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ol:I.card?g.Mv(I.card):null,dj:I.teaser?g.Mv(I.teaser):null,kf:I.icon?g.Mv(I.icon):null,Mz:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:r1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},D1(c,e)}}else lUa(a.j,e);c=
!0}}c&&(U0(a.player),a.vC())},SUa=function(a,b){var c=!1;
a.j||(a.j=PUa(a),g.H(a,a.j));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(mUa(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.Pw(b.headerText):"",g.ki(c.Ib,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ga=b.trackingParams?g.Mv(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.Mv(b.closeButton.infoCardIconRenderer.trackingParams):null,c.kf=b.icon.infoCardIconRenderer.trackingParams?
g.Mv(b.icon.infoCardIconRenderer.trackingParams):null,U0(a.player),a.vC())},TUa=function(a,b,c,d,e){if(!a.player.V().Oc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new ZTa("openUrl","click",new XTa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Pw(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.Pw(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Pw(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.Pw(b.subscriberCountWithSubscribeText)));if(b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url)var m=b.signInEndpoint.webNavigationEndpointData.url;else{var n,p;m=(null==(l=b.signInEndpoint)?void 0:null==(n=l.commandMetadata)?void 0:null==(p=n.webCommandMetadata)?void 0:p.url)||""}l={subscribeText:g.Pw(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.Pw(b.subscribedButtonText),unsubscribeCount:k||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:m};d.standalone_subscribe_button_data=l}f=new cUa(c,
"branding","branding",f,d);l=JUa(a);a.u.element.appendChild(l);f=new J1(l,Q1(a),f);f.zz();g.H(f,f);a.J[c]=f}},MUa=function(a,b){return function(){var c=g.Ba.apply(0,arguments);
a.isDisposed()||a.S.push(g.up.Tg(function(){b.apply(null,g.u(c))}))}},UUa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.xJ.prototype.Gv=g.ca(17,function(a,b){var c=g.tK(this.ob());c&&c.Gv(a,b)});
var W0={},X0=null;g.Ua(Z0,g.Pp);g.h=Z0.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Nc())return!1;Y0(this);this.startTime=a=g.Ta();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.qC();this.vj("play");-1==this.j&&this.vj("resume");this.j=1;var b=g.Oa(this);b in W0||(W0[b]=this);ITa();JTa(this,a);return!0};
g.h.stop=function(a){Y0(this);this.j=0;a&&(this.progress=1);KTa(this,this.progress);this.vj("stop");this.Ry()};
g.h.pause=function(){this.Nc()&&(Y0(this),this.j=-1,this.vj("pause"))};
g.h.qa=function(){0==this.j||this.stop(!1);this.vj("destroy");Z0.Ke.qa.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.sE=function(){this.vj("animate")};
g.h.vj=function(a){this.dispatchEvent(new LTa(a,this))};
g.Ua(LTa,g.rf);g.Ua($0,Z0);$0.prototype.C=function(){};
$0.prototype.sE=function(){this.C();$0.Ke.sE.call(this)};
$0.prototype.Ry=function(){this.C();$0.Ke.Ry.call(this)};
$0.prototype.qC=function(){this.C();$0.Ke.qC.call(this)};
g.Ua(a1,$0);a1.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(b1,g.G);b1.prototype.Ma=function(a,b,c,d){c=(0,g.Qa)(c,d||this.u);a=g.ou(a,b,c);this.j.push(a);return a};
b1.prototype.bC=function(a,b,c,d){c=(0,g.Qa)(c,d||this.u);a=g.loa(a,b,c);this.j.push(a);return a};
b1.prototype.xc=function(a){g.pu(a);g.Xb(this.j,a)};
b1.prototype.qa=function(){g.pu(this.j);this.j.length=0;g.G.prototype.qa.call(this)};g.w(f1,g.cK);g.h=f1.prototype;g.h.load=function(){g.cK.prototype.load.call(this);if(!g1(this)){var a=g.jwa(this.player.getVideoData());a?(a=e1(a,NTa(this)),h1(this,a,!1)):OTa(this)}};
g.h.unload=function(){h1(this,null);this.B&&(this.B.abort(),this.B=null);g.cK.prototype.unload.call(this)};
g.h.ag=function(a,b){return g1(this)?"loadCustomEndscreenRenderer"===a?(a=e1(b,"new"),h1(this,a),!0):null:null};
g.h.getOptions=function(){return g1(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.xb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<VUa.length;f++){var k=Math.abs(b.width-VUa[f]);if(-1===e||d>=k)e=f,d=k}d=WUa[e];this.u&&g.Jm(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
k=this.D[f],e&&k){var l=k.width*c/k.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Tm(e.element,Math.round(k.width*a.width),f);g.Pm(e.element,m,n);g.Hp(e.element,XUa);m=k.left+k.width/2;k=k.top+l/2;g.M(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Hp(e.element,WUa);g.M(e.element,d);(e=g.Sh(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.Jm(e,"height",f+"px")}}}}};
g.h.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())o1(this,this.endscreen.impressionUrls),(a=g.Tv())&&this.endscreen.visualElement&&g.Yv(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.M(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.M(b,"ytp-ce-shown");o1(this,c.impressionUrls);(b=g.Tv())&&g.Yv(b,c.visualElement);this.player.V().B&&this.player.Oa("endscreenelementshown",
a)}};
g.h.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Gp(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Gp(b,"ytp-ce-shown");this.player.V().B&&this.player.Oa("endscreenelementhidden",a)}};
g.h.q_=function(a){var b=this;a.target===window&&(new g.L(function(){for(var c=g.r(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Hp(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var VUa=[346,426,470,506,570,640,853,1280,1920],WUa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),XUa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var YTa={x6:"current",dca:"new"};var $Ta={CLOSE:"close",xca:"openUrl",SUBSCRIBE:"subscribe"},aUa={f3:"click",CLOSE:"close",a8:"hidden",Zda:"rollOut",aea:"rollOver",Wea:"shown"};var RUa={X1:"anchored",gS:"branding",CHANNEL:"channel",w6:"cta",d8:"highlightText",G9:"label",PLAYLIST:"playlist",rda:"popup",ifa:"speech",SUBSCRIBE:"subscribe",Dfa:"title",VIDEO:"video",mha:"website"},QUa={gS:"branding",Q2:"card",P6:"drawer",c8:"highlight",paa:"marker",Bda:"promotion",TEXT:"text",Pha:"widget"};g.w(x1,g.G);g.h=x1.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.Iw(a,b,{id:c,namespace:"annotations_module"});d&&this.Ua.set(a,d);e&&this.Xa.set(a,e);this.context.I.je([a])};
g.h.zz=function(){this.context.u.subscribe("resize",this.IA,this)};
g.h.tE=function(a,b,c,d,e,f){if(this.kb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.hi(this.element)};
g.h.IA=function(){};
g.h.navigate=function(a,b,c,d){var e=this,f=q1(a);if(f){var k=jUa(f,a.target),l=function(){a.j&&e.context.I.pauseVideo();var m=e.context.videoData.D||!1,n=g.or(f||"");m&&n&&(n.v||n.list)?e.context.I.ol(n.v,b,n.list,!1):g.iI(f||"","current"===k?"_top":void 0,b)};
"new"===k&&(l(),l=null);N1(this.context.logger,c,l,d);iUa(f)||(c=g.Tv(),d=b.itct,c&&d&&g.cw(c,g.Mv(d)))}};
g.h.qa=function(){this.Ua.clear();this.Xa.clear();g.G.prototype.qa.call(this)};
g.h.createElement=function(a){a=new g.V(a);g.H(this,a);return a.element};g.w(C1,x1);g.h=C1.prototype;g.h.Bp=function(){this.ma&&D1(this,this.ma)};
g.h.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.Um(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.IA=function(){var a=this.isAvailable();g.Vm(this.element,a);g.O(this.context.I.getRootNode(),g.rP.IV_DRAWER_ENABLED,a);U0(this.I)};
g.h.destroy=function(){this.I.Gv(!1);try{this.I.getRootNode().removeChild(this.C)}catch(a){}g.Ju(this.Z);g.pu(this.va);this.Ta&&this.Ta.dispose();this.D&&this.D.dispose();x1.prototype.destroy.call(this)};
g.h.iV=function(){if(this.B){N1(this.context.logger,H1(this).tracking.close);var a=g.Tv();a&&this.K&&g.cw(a,this.K);B1(this)}};
g.h.vV=function(){g.O(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.h.TW=function(){var a=g.Tv(),b=H1(this);b=b?b.kf:this.kf;a&&b&&g.aw(a,[b])};
g.h.SW=function(){var a=g.Tv(),b=H1(this);b=b?b.kf:this.kf;a&&b&&g.bw(a,[b])};
g.h.NT=function(){var a=H1(this);N1(this.context.logger,a.tracking.nR);var b=g.Tv();b&&a&&g.aw(b,[a.dj,a.kf])};
g.h.UW=function(){var a=g.Tv(),b=H1(this);a&&b&&g.bw(a,[b.dj])};
g.h.LT=function(a){var b=H1(this),c=g.Tv();this.j?a?(a=this.context.logger,N1(a,b.tracking.oD),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.dj&&g.cw(c,b.dj)):(a=this.context.logger,N1(a,b.tracking.oD),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.kf&&g.cw(c,b.kf)):(a=this.context.logger,N1(a,b.tracking.oD),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.kf&&g.cw(c,this.kf))};g.w(I1,x1);I1.prototype.zz=function(){x1.prototype.zz.call(this);yUa(this)};
I1.prototype.show=function(){x1.prototype.show.call(this);var a=g.Tv(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.aw(a,[g.Mv(b.itct)])};
I1.prototype.hide=function(){x1.prototype.hide.call(this);var a=g.Tv(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.bw(a,[g.Mv(b.itct)])};g.w(J1,I1);
J1.prototype.show=function(){if(!this.isActive){I1.prototype.show.call(this);if(!this.K){g.M(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ea:["branding-img","iv-click-target"],W:{"aria-label":"Filigrana del canale",src:a.image_url,width:a.image_width,height:a.image_height}});g.Vm(this.u,!1);var b=this.context.X.N("html5_player_branding_button_killswitch")?this.createElement({G:"div",Ea:["branding-img-container"]}):this.createElement({G:"button",Ea:["branding-img-container",
"ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=eUa(this.annotation);c&&(b=this.context.X.N("html5_player_branding_button_killswitch")?this.u:b,y1(this,b,c,this.annotation.id,a.session_data));CUa(this,a);this.K=!0}g.Vm(this.element,!0);this.isActive=!0;this.u&&zUa(this,this.u)}};
J1.prototype.hide=function(){this.isActive&&(I1.prototype.hide.call(this),g.Vm(this.element,!1),this.isActive=!1)};
J1.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);I1.prototype.destroy.call(this)};g.w(K1,I1);g.h=K1.prototype;g.h.show=function(){this.isActive||(I1.prototype.show.call(this),this.Y||(EUa(this),this.Y=!0),g.Vm(this.element,!0),g.Ei(function(){g.Gp(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,M1(this),FUa(this),GUa(this,this.J))};
g.h.hide=function(){this.isActive&&(g.M(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.h.tE=function(a,b,c,d,e,f){return this.isCollapsed?!1:I1.prototype.tE.call(this,a,b,c,d,e,f)};
g.h.bW=function(a){this.S=!0;L1(this,500,a)};
g.h.aW=function(){this.S=!1;HUa(this)};
g.h.VV=function(a){a.stopPropagation();this.hide()};
g.h.WV=function(a){a.stopPropagation();M1(this);this.isCollapsed=!0;g.M(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.h.destroy=function(){this.D.dispose();I1.prototype.destroy.call(this)};g.w(O1,g.cK);g.h=O1.prototype;g.h.ag=function(a,b){if(!UUa(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.l_(b))&&P1(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(oUa(this.j,b),U0(this.player)),!0}return null};
g.h.getOptions=function(){return UUa(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Js=function(){var a=this.player.V(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.vQ||a.Z.get(b.videoId)||g.vE(b)||g.wE(b)?!0:!1};
g.h.vC=function(){if(this.B){var a=this.player.Ya().getVideoContentRect(!0);g.Tm(this.B.element,a.width,a.height);g.Pm(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Fk();a=this.j;b=b.width;g.O(a.C,"iv-drawer-small",426>=b);g.O(a.C,"iv-drawer-big",1280<=b)}};
g.h.OT=function(a){KUa(this,a.state);g.U(a.state,2)&&(this.Ph()&&this.Nl()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Gv(!1))};
g.h.load=function(){function a(k){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(k=g.Ar(k)&&k.responseXML?k.responseXML:null)&&(P1(b,k),g.M(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.cK.prototype.load.call(this);KUa(this,this.player.yb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Wr()&&(a=MUa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().Z.get(d);f&&NUa(e,f);f=f&&(f.NA||f.kx);if(!c.Wm||f)c.Ua?this.C=g.Gr(c.Ua,e):(this.Im=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Im));
g.EJ(this.player,this.B.element,4);this.vC();(f=g.vE(c))&&SUa(this,f);(f=g.wE(c))&&f.featuredChannel&&TUa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.h.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ua&&(this.Im&&(this.player.removeEventListener("videodatachange",this.Im),this.Im=null),this.C=g.Gr(b.Ua,a))};
g.h.unload=function(){this.player.Nf("annotations_module");for(var a=g.r(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.K=null;this.j&&(this.j.destroy(),this.j=null,U0(this.player));this.C&&(this.C.abort(),this.C=null);this.J={};this.u.hide();g.cK.prototype.unload.call(this);this.B.detach();this.Im&&(this.player.removeEventListener("videodatachange",this.Im),this.Im=null)};
g.h.WP=function(a){a===this.player.getVideoData().videoId&&(this.loaded?OUa(this):this.load())};
g.h.Ph=function(){return!!this.j&&this.j.isAvailable()};
g.h.Nl=function(){return!!this.j&&this.j.B};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Ph();this.j&&(a?c?A1(this.j,c,b):A1(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):B1(this.j))};
g.h.Gv=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.qa=function(){this.player.V().Z.unsubscribe("vast_info_card_add",this.WP,this);g.Gp(this.player.getRootNode(),g.rP.IV_DRAWER_OPEN);for(var a=this.S,b=g.up,c=0,d=a.length;c<d;c++)b.tj(a[c]);this.S.length=0;g.cK.prototype.qa.call(this)};
g.h.createElement=function(a){a=new g.V(a);g.H(this,a);return a.element};g.bK("annotations_module",O1);g.bK("creatorendscreen",f1);})(_yt_player);
